version: '3'

services:
  web:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - ENV=production
    volumes:
      - ./:/app
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
